name: allpass
description: A password manage application.

version: 1.6.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 动画
  animations: ^2.0.0
#  # IOS图标
#  cupertino_icons: ^1.0.2
  # 权限申请
  permission_handler: ^7.1.0
  # 弹出底部通知
  fluttertoast: ^8.0.6
  # 数据库
  sqflite: ^2.0.0
  # 应用路径
  path_provider: ^2.0.1
  # 密码加密
  encrypt: ^4.1.0
  # 文件管理
  file_picker: ^3.0.1
  # 路径选择
  filesystem_picker: ^1.0.4
  # 打开链接
  url_launcher: ^6.0.3
  # 状态管理
  provider: ^5.0.0
  # 路由管理
  fluro: ^2.0.3
  # 持久化
  shared_preferences: ^2.0.5
  # 依赖注入
  get_it: ^7.0.0
  # 生物识别
  local_auth: ^1.1.5
  # 屏幕尺寸管理
  flutter_screenutil: ^0.7.0
  # 汉字转拼音
  lpinyin: ^2.0.1
  # 网络请求
  dio: ^4.0.0
  # 设备信息
  device_info: ^2.0.0
  # 分享功能
  share: ^2.0.1
  # 密钥存储
  flutter_secure_storage: ^4.2.0
  # XML解析
  xml: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/import_step1.jpg
    - assets/images/import_step2.jpg
    - assets/images/import_step3.jpg
    - assets/images/import_step4.jpg
    - assets/images/import_step5.png

  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
